name: Kubernetes Blog
markdown: kramdown
#permalink: /:year/:month/:day/:title
paginate: 5
#theme: jekyll-theme-dinky
#remote_theme: pages-themes/dinky@v0.2.0
#plugins:
#- jekyll-remote-theme

theme: jekyll-theme-time-machine
