apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-volume
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
  storageClassName: sata
  volumeMode: Filesystem

